const courses=[
 {n:'01',tag:'أساسيات',title:'كيف يتحدث الريموت مع السيارة؟',desc:'فهم التردد، الإطار، الهوية، والتشفير بلغة بسيطة.',meta:'8 دقائق',type:'قراءة',done:true},
 {n:'02',tag:'أساسيات',title:'رحلة الإشارة: من الزر إلى وحدة التحكم',desc:'تتبع الإشارة في محاكاة مرئية واكتشف نقاط الفشل المحتملة.',meta:'12 دقيقة',type:'تفاعلي',done:false},
 {n:'03',tag:'أجهزة',title:'اختيار الجهاز المناسب للمهمة',desc:'مقارنة OBD-II Trainer وBench Programmer ومحلل RF للقراءة فقط.',meta:'14 دقيقة',type:'مختبر',done:false},
 {n:'04',tag:'تشخيص',title:'التشخيص قبل التسجيل',desc:'قائمة تحقق تمنعك من القفز إلى الإجراء الخطأ.',meta:'12 دقيقة',type:'سيناريو',done:false}
];
const steps=[['تحقق من التفويض والسياق','هوية المالك، نطاق العمل، وبيئة التدريب'],['طابق المنصة والجهاز','لا تبدأ قبل فهم التوافق النظري'],['افحص الطاقة والاتصال','قراءة الحالة دون إرسال أوامر'],['اختر تسلسلًا تدريبيًا','طبّق المنطق على بيانات وهمية'],['وثّق النتيجة','سجّل ما تعلّمته وأي إشارات تحذير']];
const quizzes=[
 {q:'ما أول قرار مسؤول قبل اختيار أي جهاز؟',a:['اختيار أعلى جهاز سعرًا','التحقق من التفويض والمنصة','ضغط زر التسجيل مباشرة','تغيير تردد الريموت'],c:1,ex:'السياق القانوني والتوافق يسبقان الأداة. الجهاز لا يعوّض غياب التفويض أو البيانات الصحيحة.'},
 {q:'ما المقصود بالتزامن في سياق الريموت؟',a:['زيادة صوت البوق','مواءمة حالة الريموت مع وحدة التحكم','تغيير بطارية السيارة','قراءة رقم اللوحة'],c:1,ex:'التزامن هو مفهوم مواءمة الحالة/العداد بين طرفين، وليس مجرد إرسال إشارة عشوائية.'},
 {q:'أي جهاز في المختبر مخصص للقراءة فقط؟',a:['RF Analyzer','Bench Programmer','OBD-II Trainer','ولا واحد'],c:0,ex:'محلل RF للقراءة فقط يساعد على فهم شكل الإشارة دون إرسال أو تعديل.'},
 {q:'متى توثّق النتيجة؟',a:['قبل أي تحقق','بعد كل خطوة ذات معنى','لا حاجة للتوثيق','فقط عند الفشل'],c:1,ex:'التوثيق جزء من العمل المسؤول: يسجل الحالة، القرار، والنتيجة دون الاحتفاظ ببيانات حساسة.'}
];
let state={view:'dashboard',step:0,quiz:0,selected:null,score:0,points:120};
try{const saved=JSON.parse(localStorage.getItem('cklab-state'));if(saved)state={...state,...saved}}catch(e){}
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem('cklab-state',JSON.stringify({step:state.step,quiz:state.quiz,score:state.score,points:state.points}));$('#points').textContent=state.points+' XP';}
function showView(view){state.view=view;$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===view));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={dashboard:'لوحة التعلم',learn:'مسارات التعلم',simulator:'المحاكي الآمن',practice:'بنك التمارين',tutor:'مساعد AI'};$('#page-title').textContent=titles[view];if(view==='learn')renderCourses();if(view==='simulator')renderSteps();if(view==='practice')renderQuiz();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));
function renderCourses(filter='الكل'){const list=$('#course-list');list.innerHTML=courses.filter(c=>filter==='الكل'||c.tag===filter).map(c=>`<article class="course-card ${c.done?'done':''}"><div class="course-index">${c.done?'✓':c.n}</div><div class="course-main"><h3>${c.title}</h3><p>${c.desc}</p><div class="course-meta"><span>${c.type}</span><span>${c.meta}</span><span>${c.tag}</span></div></div><div class="course-arrow">←</div></article>`).join('')}
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCourses(b.textContent)}));
function renderSteps(){const list=$('#steps-list');list.innerHTML=steps.map((s,i)=>`<div class="step-item ${i===state.step?'active':''} ${i<state.step?'done':''}"><div class="step-circle">${i<state.step?'✓':i+1}</div><div><b>${s[0]}</b><small>${s[1]}</small></div></div>`).join('');$('#sim-progress-text').textContent=`${state.step} / 5 خطوات`;$('#sim-bar').style.width=(state.step/5*100)+'%';$('#step-tip').textContent=state.step===0?'ابدأ بإنشاء سياق آمن: تحقق من التفويض وبيانات المنصة قبل اختيار الإجراء.':steps[Math.min(state.step,4)][1]}
$('#start-sim').addEventListener('click',()=>{if(state.step<5){state.step++;const line=document.createElement('div');line.className='terminal-line '+(state.step===3?'warn':'ok');line.textContent=`> STEP ${String(state.step).padStart(2,'0')} / ${steps[state.step-1]?.[0]||'اكتمل التسلسل'} ... ${state.step===3?'تحذير تعليمي: تحقق يدوي مطلوب':'OK — محاكاة فقط'}`;$('#terminal').appendChild(line);renderSteps();save();if(state.step===5){$('#start-sim').textContent='إعادة المحاكاة ↻';state.points+=20;save()}}else{state.step=0;$('#terminal').innerHTML='<div class="terminal-line muted-line">CARKEY LAB / SIMULATION KERNEL v1.4</div><div class="terminal-line">> اختر المنصة والجهاز ثم ابدأ التسلسل.</div>';$('#start-sim').innerHTML='ابدأ التسلسل <span>←</span>';renderSteps()}});
function renderQuiz(){const q=quizzes[state.quiz];$('#quiz-number').textContent=String(state.quiz+1).padStart(2,'0');$('#quiz-score').textContent=state.score;$('#quiz-content').innerHTML=`<h2 class="quiz-question">${q.q}</h2><div class="answers">${q.a.map((a,i)=>`<button class="answer ${state.selected===i?'selected':''}" data-answer="${i}">${String.fromCharCode(1571+i)}. ${a}</button>`).join('')}</div>`;$$('[data-answer]').forEach(b=>b.addEventListener('click',()=>{state.selected=+b.dataset.answer;$$('.answer').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));$('#prev-quiz').disabled=state.quiz===0;$('#next-quiz').textContent=state.selected===null?'تحقق من الإجابة ←':(state.quiz===quizzes.length-1?'إنهاء التمرين ←':'السؤال التالي ←')}
$('#next-quiz').addEventListener('click',()=>{if(state.selected===null){return alert('اختر إجابة أولًا لتتحقق من فهمك.')}const q=quizzes[state.quiz],correct=state.selected===q.c;$$('.answer')[state.selected].classList.add(correct?'correct':'wrong');if(correct){state.score+=25;state.points+=10}alert((correct?'إجابة صحيحة. ':'ليست الإجابة الأدق. ')+q.ex);if(state.quiz<quizzes.length-1){state.quiz++;state.selected=null;renderQuiz()}else{state.quiz=0;state.selected=null}save()});$('#prev-quiz').addEventListener('click',()=>{if(state.quiz>0){state.quiz--;state.selected=null;renderQuiz()}});
const replies={
 'ما هو التزامن؟':'التزامن هو مواءمة حالة الريموت مع وحدة التحكم بحيث يفهم الطرفان نفس السياق. في التدريب، فكّر فيه كـ«اتفاق على الحالة» وليس كإرسال إشارة عشوائية.',
 'أعطني تلميحًا':'التلميح: قبل أن تفكر في الجهاز، اسأل نفسك سؤالين: هل لدي تفويض واضح؟ وهل أعرف المنصة التي أتعامل معها؟',
 'ما الخطوة الآمنة الأولى؟':'الخطوة الأولى هي بناء سياق آمن: التحقق من التفويض، تسجيل بيانات المنصة العامة، والتأكد أنك في بيئة تدريب أو لديك إجراء مصنع موثّق.',
 'default':'سؤال ممتاز. ضمن هذا المختبر، نبدأ من المبدأ: افهم المنصة، افحص الحالة دون تعديل، ثم اختر إجراءً تدريبيًا موثقًا. لا تدخل أي أرقام مفاتيح أو بيانات مركبات حقيقية.'};
function addMessage(text,who='bot'){const box=$('#chat-messages');const div=document.createElement('div');div.className='message '+who;div.textContent=text;box.appendChild(div);box.scrollTop=box.scrollHeight}
$$('.suggestions button').forEach(b=>b.addEventListener('click',()=>{addMessage(b.textContent,'user');setTimeout(()=>addMessage(replies[b.textContent]||replies.default),220)}));$('#chat-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#chat-input'),text=input.value.trim();if(!text)return;addMessage(text,'user');input.value='';setTimeout(()=>{const key=Object.keys(replies).find(k=>text.includes(k.replace('؟','')));addMessage(replies[key||'default'])},220)});
$('#mastery-bar').style.width='24%';save();showView('dashboard');